const info = [
  {
    id: 1,
    src: "/images/sunflower.jpg",
    title: "Sunflower",
    alt: "",
    desc: "By Post Malone, Swae Lee .",
  },
  {
    id: 2,
    src: "/images/onesided.jpg",
    title: "One Sided",
    alt: "",
    desc: "By Preston Pablo.",
  },
  {
    id: 3,
    src: "/images/honey.jpg",
    title: "Honey, I'm Good",
    alt: "",
    desc: "By Andy Grammer.",
  },
  {
    id: 4,
    src: "/images/oldtown.jpg",
    title: "Old Town Road",
    alt: "",
    desc: "By Lil Nas X.",
  },
  {
    id: 5,
    src: "/images/upside.jpg",
    title: "Upside Down",
    desc: "By JVKE.",
  },
  {
    id: 6,
    src: "/images/mtob.png",
    title: "M To The B",
    alt: "",
    desc: "By Millie B.",
  },
  {
    id: 7,
    src: "/images/breaking_me.png",
    title: "Breaking Me",
    alt: "",
    desc: "By Topic, A7S.",
  },
  {
    id: 8,
    src: "/images/highhopes.jpg",
    title: "High Hopes",
    alt: "",
    desc: "By Panic! At The Disco.",
  },
  {
    id: 9,
    src: "/images/ride.jpg",
    title: "Ride",
    alt: "",
    desc: "By Twenty One Pilots.",
  },
  {
    id: 10,
    src: "/images/cradles.jpg",
    title: "Cradles",
    alt: "",
    desc: "By Sub Urban.",
  },
  {
    id: 11,
    src: "/images/story.jpg",
    title: "Love Story",
    alt: "",
    desc: "By Tayler Swift.",
  },
  {
    id: 12,
    src: "/images/woah.jpg",
    title: "Woah (Feat. D3Mstreet)",
    alt: "",
    desc: "By Krypto9095, D3Mstreet.",
  },
  {
    id: 13,
    src: "/images/playdate.jpg",
    title: "Play Date",
    alt: "",
    desc: "By Melanie Martinez.",
  },
  {
    id: 14,
    src: "/images/sucker.png",
    title: "Sucker",
    alt: "",
    desc: "By Jonas Brothers.",
  },
  {
    id: 15,
    src: "/images/middle.jpg",
    title: "The Middle",
    alt: "",
    desc: "By Maren Morris, Zedd, Grey.",
  },
  
];

export default info;
